### ISSUE TITLE
Note: I'm still not a fan of using globals and would like to see something like dependency injection via function parameters used instead.

### ISSUE THREAD

**Issue by KillariDev** [DarkFlorist/TheInterceptor#58]
Note: I'm still not a fan of using globals and would like to see something like dependency injection via function parameters used instead.

_Originally posted by @MicahZoltu in https://github.com/DarkFlorist/TheInterceptor/pull/57#discussion_r1050892350_

**Comment by KillariDev** [comment]
fixed for inpage

**Comment by MicahZoltu** [comment]
Doesn't the same issue still exist for background and maybe popup?
